export enum TipoDepartamentoEnum {
    ADMINISTRATIVO = 'ADMINISTRATIVO',
    FINANCEIRO = 'FINANCEIRO',
    RECURSOS_HUMANOS = 'RECURSOS_HUMANOS',
    COMERCIAL = 'COMERCIAL',
    OPERACIONAL = 'OPERACIONAL',
    MARKETING = 'MARKETING',
}